# Generated by Django 5.2.1 on 2025-08-21 08:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_application_admission_type_and_more'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Fan kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Test fani',
                'verbose_name_plural': 'Test fanlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.IntegerField(default=55, verbose_name="O'tish balli")),
                ('time_limit', models.IntegerField(default=60, verbose_name='Vaqt chegarasi (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_config', to='programs.program', verbose_name="Yo'nalish")),
                ('subject_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_tests_1', to='quizes.subject', verbose_name='1-fan')),
                ('subject_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_tests_2', to='quizes.subject', verbose_name='2-fan')),
            ],
            options={
                'verbose_name': "Yo'nalish test sozlamasi",
                'verbose_name_plural': "Yo'nalish test sozlamalari",
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('subject_1', '1-fan'), ('subject_2', '2-fan')], max_length=10, verbose_name='Fan turi')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Savol raqami')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=500, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=500, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('program_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizes.programtest', verbose_name="Yo'nalish testi")),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['program_test', 'subject_type', 'question_number'],
                'unique_together': {('program_test', 'subject_type', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Urinish raqami')),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('completed', 'Yakunlangan'), ('timed_out', 'Vaqt tugagan')], default='started', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Vaqt (sekund)')),
                ('subject_1_score', models.IntegerField(default=0, verbose_name='1-fan ball')),
                ('subject_2_score', models.IntegerField(default=0, verbose_name='2-fan ball')),
                ('total_score', models.IntegerField(default=0, verbose_name='Jami ball')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('is_passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='applications.application', verbose_name='Ariza')),
                ('program_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizes.programtest', verbose_name="Yo'nalish testi")),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
                'unique_together': {('application', 'program_test', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_total_score', models.IntegerField(default=0, verbose_name='Eng yaxshi ball')),
                ('best_percentage', models.FloatField(default=0.0, verbose_name='Eng yaxshi foiz')),
                ('is_test_passed', models.BooleanField(default=False, verbose_name="Test o'tdi")),
                ('best_subject_1_score', models.IntegerField(default=0, verbose_name='1-fan eng yaxshi')),
                ('best_subject_2_score', models.IntegerField(default=0, verbose_name='2-fan eng yaxshi')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Jami urinishlar')),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi urinish')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='applications.application', verbose_name='Ariza')),
                ('best_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.testattempt', verbose_name='Eng yaxshi urinish')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-best_total_score'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(verbose_name="To'g'ri")),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Javob vaqti')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.question', verbose_name='Savol')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizes.testattempt', verbose_name='Test urinishi')),
            ],
            options={
                'verbose_name': 'Test javobi',
                'verbose_name_plural': 'Test javoblari',
                'ordering': ['question__subject_type', 'question__question_number'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
