# Generated by Django 5.2.1 on 2025-06-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Viloyat yoki shahar nomi')),
            ],
            options={
                'verbose_name': 'Viloyat yoki shahar',
                'verbose_name_plural': 'Viloyat va shaharlar',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tuman nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='regions.region', verbose_name='Viloyat yoki shahar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'unique_together': {('name', 'region')},
            },
        ),
    ]
