# Generated by Django 5.2.1 on 2025-06-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_country_alter_region_unique_together_region_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Davlat nomini kiriting (masalan: O‘zbekiston, Qozog‘iston)', max_length=100, unique=True, verbose_name='Davlat nomi'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(help_text='Tuman yoki shaharcha nomini kiriting (masalan: Olmazor)', max_length=100, verbose_name='Tuman nomi'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(help_text='Ushbu tuman tegishli bo‘lgan viloyat yoki shaharni tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='regions.region', verbose_name='Viloyat yoki shahar'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(help_text='Ushbu viloyat tegishli bo‘lgan davlatni tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='regions.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Viloyat yoki shahar nomini kiriting (masalan: Toshkent)', max_length=100, verbose_name='Viloyat yoki shahar nomi'),
        ),
    ]
