# Generated by Django 5.2.1 on 2025-06-03 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abituriyentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'abituriyent'}, on_delete=django.db.models.deletion.CASCADE, related_name='abituriyent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='marketingprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'marketing'}, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='miniadminprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'mini_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='mini_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
