# Generated by Django 5.2.1 on 2025-07-07 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_abituriyentprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abituriyentprofile',
            name='image',
            field=models.ImageField(blank=True, help_text="3x4 o'lchamdagi rasm (JPG, PNG)", null=True, upload_to='users/abituriyents/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='3x4 rasm'),
        ),
        migrations.AlterField(
            model_name='abituriyentprofile',
            name='passport_file',
            field=models.FileField(blank=True, help_text='Pasport nusxasi (PDF, JPG, PNG)', null=True, upload_to='users/abituriyents/passports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Pasport nusxasi'),
        ),
    ]
