# Generated by Django 5.2.1 on 2025-06-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Universitet filiali nomini kiriting (masalan: Toshkent, Andijon, Nukus)', max_length=100, verbose_name='Filial nomi')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='EducationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Taʼlim shaklini kiriting (masalan: Kunduzgi, Sirtqi, Kechki)', max_length=100, verbose_name='Taʼlim shakli')),
            ],
            options={
                'verbose_name': 'Taʼlim shakli',
                'verbose_name_plural': 'Taʼlim shakllari',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Taʼlim darajasini kiriting (masalan: Bakalavr, Magistr)', max_length=100, verbose_name='Taʼlim darajasi')),
            ],
            options={
                'verbose_name': 'Taʼlim darajasi',
                'verbose_name_plural': 'Taʼlim darajalari',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Yo‘nalish uchun rasm yuklang (ixtiyoriy)', null=True, upload_to='programs/program/', verbose_name='Yo‘nalish rasmi')),
                ('name', models.CharField(help_text='Yo‘nalish nomini kiriting (masalan: Dasturiy injiniring, Biologiya)', max_length=200, verbose_name='Yo‘nalish nomi')),
                ('code', models.CharField(help_text='Yo‘nalish kodini kiriting (masalan: 5330200)', max_length=100, verbose_name='Yo‘nalish kodi')),
                ('tuition_fee', models.CharField(help_text='Yillik kontrakt summasini kiriting (masalan: 12 000 000 so‘m)', max_length=255, verbose_name='Kontrakt summasi')),
                ('study_duration', models.CharField(help_text='O‘qish muddatini kiriting (masalan: 4 yil, 2 yil)', max_length=100, verbose_name='O‘qish muddati')),
                ('contract_series', models.CharField(help_text='Shartnoma seriyasini kiriting (masalan: 2025-BK)', max_length=100, verbose_name='Shartnoma seriyasi')),
                ('branch', models.ForeignKey(help_text='Yo‘nalish mavjud bo‘lgan filialni tanlang', on_delete=django.db.models.deletion.CASCADE, to='programs.branch', verbose_name='Filial')),
                ('education_form', models.ForeignKey(help_text='Yo‘nalish tegishli bo‘lgan taʼlim shaklini tanlang', on_delete=django.db.models.deletion.CASCADE, to='programs.educationform', verbose_name='Taʼlim shakli')),
                ('education_level', models.ForeignKey(help_text='Yo‘nalish tegishli bo‘lgan taʼlim darajasini tanlang', on_delete=django.db.models.deletion.CASCADE, to='programs.educationlevel', verbose_name='Taʼlim darajasi')),
            ],
            options={
                'verbose_name': 'Yo‘nalish',
                'verbose_name_plural': 'Yo‘nalishlar',
            },
        ),
    ]
