# Generated by Django 5.2.1 on 2025-06-19 20:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_contract_type', models.CharField(choices=[('ikki_tomonlama', 'Ikki tomonlama'), ('uch_tomonlama', 'Uch tomonlama')], default='ikki_tomonlama', max_length=20, verbose_name='Standart shartnoma turi')),
                ('auto_generate_pdf', models.BooleanField(default=True, help_text="Agar faol bo'lsa, HTML dan PDF yaratishga harakat qiladi", verbose_name='Avtomatik PDF yaratish')),
                ('pdf_page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=10, verbose_name="PDF sahifa o'lchami")),
                ('company_name', models.CharField(default="Ta'lim muassasasi", max_length=200, verbose_name='Muassasa nomi')),
                ('company_address', models.TextField(blank=True, verbose_name='Muassasa manzili')),
                ('director_name', models.CharField(blank=True, max_length=100, verbose_name='Direktor F.I.Sh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shartnoma sozlamasi',
                'verbose_name_plural': 'Shartnoma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: 'Ikki tomonlama shartnoma' yoki 'Uch tomonlama shartnoma'", max_length=200, verbose_name='Shablon nomi')),
                ('ikki_tomonlama', ckeditor.fields.RichTextField(blank=True, help_text='Placeholder lar: {{TALABA_ISMI}}, {{TELEFON}}, {{FILIAL}}, {{YONALISH}}, {{TALIM_DARAJASI}}, {{TALIM_SHAKLI}}, {{QABUL_TURI}}, {{SANA}}', null=True, verbose_name='Ikki tomonlama shartnoma shabloni')),
                ('uch_tomonlama', ckeditor.fields.RichTextField(blank=True, help_text='Placeholder lar: {{TALABA_ISMI}}, {{TELEFON}}, {{FILIAL}}, {{YONALISH}}, {{TALIM_DARAJASI}}, {{TALIM_SHAKLI}}, {{QABUL_TURI}}, {{SANA}}, {{OTA_ONA_ISMI}}, {{OTA_ONA_TELEFON}}', null=True, verbose_name='Uch tomonlama shartnoma shabloni')),
                ('is_active', models.BooleanField(default=True, help_text="Faqat bitta shablon faol bo'lishi mumkin", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Shartnoma shabloni',
                'verbose_name_plural': 'Shartnoma shablonlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
