# Generated by Django 5.2.1 on 2025-06-03 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0002_country_alter_region_unique_together_region_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taʼlim turi')),
            ],
            options={
                'verbose_name': 'Taʼlim turi',
                'verbose_name_plural': 'Taʼlim turlari',
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Muassasa turi')),
            ],
            options={
                'verbose_name': 'Muassasa turi',
                'verbose_name_plural': 'Muassasa turlari',
            },
        ),
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Diplom raqami')),
                ('university_name', models.TextField(verbose_name='Universitet nomi')),
                ('graduation_year', models.CharField(max_length=4, verbose_name='Bitirgan yil')),
                ('diploma_file', models.FileField(upload_to='diploms/', verbose_name='Diplom fayli')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Viloyat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.educationtype', verbose_name='Taʼlim turi')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.institutiontype', verbose_name='Muassasa turi')),
            ],
            options={
                'verbose_name': 'Diplom',
                'verbose_name_plural': 'Diplomlar',
            },
        ),
        migrations.CreateModel(
            name='TransferDiplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField(verbose_name='Universitet nomi')),
                ('transcript_file', models.FileField(upload_to='transcripts/', verbose_name='Transcript fayli')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.country', verbose_name='Davlat')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.course', verbose_name='Kurs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Perevod diplomi',
                'verbose_name_plural': 'Perevod diplomlari',
            },
        ),
    ]
