# Generated by Django 5.2.1 on 2025-06-03 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0001_initial'),
        ('regions', '0003_alter_country_name_alter_district_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Kurs nomini kiriting (masalan: 1-kurs, 2-kurs)', max_length=255, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='diploma_file',
            field=models.FileField(help_text='Diplom faylini yuklang (PDF yoki rasm formatida)', upload_to='diploms/', verbose_name='Diplom fayli'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='district',
            field=models.ForeignKey(help_text='Universitet joylashgan tumanni tanlang', on_delete=django.db.models.deletion.CASCADE, to='regions.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='education_type',
            field=models.ForeignKey(help_text='Diplom tegishli bo‘lgan taʼlim turini tanlang', on_delete=django.db.models.deletion.CASCADE, to='diploms.educationtype', verbose_name='Taʼlim turi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='graduation_year',
            field=models.CharField(help_text='Bitirgan yilni 4 xonali raqamda kiriting (masalan: 2022)', max_length=4, verbose_name='Bitirgan yil'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='institution_type',
            field=models.ForeignKey(help_text='Diplom berilgan muassasa turini tanlang', on_delete=django.db.models.deletion.CASCADE, to='diploms.institutiontype', verbose_name='Muassasa turi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='region',
            field=models.ForeignKey(help_text='Universitet joylashgan viloyatni tanlang', on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='serial_number',
            field=models.CharField(help_text='Diplomning seriya va raqamini kiriting', max_length=100, verbose_name='Diplom raqami'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='university_name',
            field=models.TextField(help_text='Universitetning to‘liq nomini kiriting', verbose_name='Universitet nomi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='user',
            field=models.OneToOneField(help_text='Diplomga ega foydalanuvchini tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='name',
            field=models.CharField(help_text='Taʼlim turini kiriting (masalan: Bakalavr, Magistratura)', max_length=100, verbose_name='Taʼlim turi'),
        ),
        migrations.AlterField(
            model_name='institutiontype',
            name='name',
            field=models.CharField(help_text='Muassasa turini kiriting (masalan: Universitet, Institut)', max_length=100, verbose_name='Muassasa turi'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='country',
            field=models.ForeignKey(help_text='Universitet joylashgan davlatni tanlang', on_delete=django.db.models.deletion.CASCADE, to='regions.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='target_course',
            field=models.ForeignKey(help_text='Qabul qilinayotgan kursni tanlang', on_delete=django.db.models.deletion.CASCADE, to='diploms.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='transcript_file',
            field=models.FileField(help_text='Transcript faylini yuklang (PDF yoki rasm formatida)', upload_to='transcripts/', verbose_name='Transcript fayli'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='university_name',
            field=models.TextField(help_text='Perevod qilinayotgan universitetning to‘liq nomini kiriting', verbose_name='Universitet nomi'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='user',
            field=models.OneToOneField(help_text='Perevod diplomi egasini tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
