# Generated by Django 5.2.1 on 2025-06-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diploms', '0002_alter_course_name_alter_diplom_diploma_file_and_more'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('regular', '1-kurs (Yangi qabul)'), ('transfer', 'Perevod (O‘qishni ko‘chirish)')], default='regular', max_length=20, verbose_name='Qabul turi')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Shartnoma fayli')),
                ('status', models.CharField(choices=[('pending', 'Yuborilgan'), ('review', 'Ko‘rib chiqilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan sana')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.branch', verbose_name='Filial')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='diploms.course', verbose_name='Kurs')),
                ('diplom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='diploms.diplom', verbose_name='Diplom')),
                ('education_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.educationform', verbose_name='Taʼlim shakli')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.educationlevel', verbose_name='Taʼlim darajasi')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program', verbose_name='Yo‘nalish')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ko‘rib chiquvchi xodim')),
                ('transfer_diplom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='diploms.transferdiplom', verbose_name='Perevod diplomi')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Barcha arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
