# Generated by Django 5.2.1 on 2025-06-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admission_type',
            field=models.CharField(choices=[('yangi_qabul', '1-kurs (Yangi qabul)'), ('perevod', "Perevod (O'qishni ko'chirish)")], default='yangi_qabul', max_length=20, verbose_name='Qabul turi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Shartnoma fayli'),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiquvchi xodim"),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('topshirildi', 'Ariza topshirildi'), ('korib_chiqilmoqda', "Ko'rib chiqilmoqda"), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], default='topshirildi', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana"),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'abituriyent'}, on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
