# Generated by Django 5.2.1 on 2025-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_admission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test topshirdi'),
        ),
        migrations.AddField(
            model_name='application',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test sanasi'),
        ),
        migrations.AddField(
            model_name='application',
            name='test_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name="Test o'tdi"),
        ),
        migrations.AddField(
            model_name='application',
            name='test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Test balli'),
        ),
    ]
